name: Continuous Deployment to Staging

on:
  push:
    branches: ["development"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧪 1. SETUP PHP 8.2 UNTUK COMPOSER (Sesuai spek lokal & Azure)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, dom, fileinfo, pdo, pdo_pgsql

      # 📥 2. RITUAL INSTALASI BERSIH JINAK PLATFORM (Sama kayak di lokalmu tadi!)
      - name: Install PHP Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

      # 📦 3. SETUP FRONTEND ASET (NPM)
      - name: Setup Node.js v16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"

      - name: Install NPM & Compile Assets
        run: |
          npm ci
          npm run prod

      # 🚀 4. DEPLOY MASAL KE AZURE NATIVE PHP STACK
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "absensi-app"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
