name: Continuous Deployment to Staging

on:
  workflow_run:
    workflows: ["Automated PHPUnit Testing", "Laravel Frontend CI"]
    types:
      - completed

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.head_branch == 'development' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 📦 AMBIL ASET FRONTEND: Download hasil compile Laravel Mix v6 dari workflow sebelah
      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-assets
          path: public/

      # 🚀 DEPLOY KE AZURE APP SERVICE: Menerbangkan kode backend + frontend utuh
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Microsoft.Web-WebApp-Portal-00fe6bab-85ea" # 💡 Ini nama default Web App kamu sesuai ARM Template tadi, nanti kalau kamu ubah namanya tinggal disesuaikan ya bub!
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
